require "user.options"
require "user.keymaps"
require "user.commands"
require "user.plugins"
require "user.nvim-tree"
require "user.colorscheme"
require "user.telescope"
require "user.treesitter"

-- require "user.project"
require "user.bufferline"
require "user.lualine"
require "user.alpha"
require "user.whichkey"
require "user.toggleterm"
